version: "3.3"

networks:
    mpmeet-lan:
        driver: bridge
        ipam:
            config:
                - subnet: 10.0.6.0/24
    mpmeet-wan:
        driver: bridge
        ipam:
            config:
                - subnet: 172.16.6.0/24
# Volumes:
volumes:
    # Thằng này thì phải tạo volume thì mới để dữ liệu ra ngoài host được, mount trực tiếp không ăn;
    mssql-data:
        driver: local
        driver_opts:
            type: volume
            device: ./MSSQL/mssql-data
            o: bind

# Containers:
services:
    mssql-server:
        #image: "mcr.microsoft.com/mssql/server:2017-latest-ubuntu"
        #image: 'mcr.microsoft.com/mssql/server:2022-CU14-ubuntu-22.04'
        build:
            context: "./MSSQL/DbConfig"
        container_name: mssql-server
        restart: "no"
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=123@123a
            - MSSQL_PID=Express
        networks:
            mpmeet-lan:
                ipv4_address: 10.0.6.20
        volumes:
            - ./MSSQL/:/Scripts
            - ./MSSQL/logs:/var/log
            - ./MSSQL/mnt:/mnt
            # - ./MSSQL/mssql-data/data/techtechcare_eShopSolution_log.ldf:/var/opt/mssql/data/techtechcare_eShopSolution_log.ldf
            # - ./MSSQL/mssql-data/data/techtechcare_eShopSolution.mdf:/var/opt/mssql/data/techtechcare_eShopSolution.mdf
            - ./MSSQL/mssql-data2/data/:/var/opt/mssql/data/
            # - mssql-data:/var/opt/mssql
            # - ./MSSQL/mssql-data:/var/opt/mssql
        ports:
            - 1435:1433

    # sqlcmd:
    #     image: "mcr.microsoft.com/mssql-tools"
    #     depends_on:
    #     - "mssql-server"
    #     entrypoint: /bin/sh -c 'until nc -z "mssql-server" 1435; do echo "Waiting for SQL Server..."; sleep 5; done; sqlcmd -S "mssql-server" -U SA -P 123@123a -Q "USE [master]; CREATE DATABASE techtechcare_eShopSolution ON (FILENAME = '/var/opt/mssql/data/techtechcare_eShopSolution.mdf'), (FILENAME = '/var/opt/mssql/data/techtechcare_eShopSolution_log.ldf') FOR ATTACH;"'    

    web-api:
        image: "appsvc/dotnetcore:3.1-latest_20200522.6"
        container_name: web-api
        restart: always
        environment:
            WEBSITE_ROLE_INSTANCE_ID: localRoleInstance
            WEBSITE_INSTANCE_ID: localInstance
            ## Connection
            #Connection: "Server=mssql-server;initial catalog=techtechcare_eShopSolution;user id=sa;password=123@123a"

        networks:
            mpmeet-lan:
                ipv4_address: 10.0.6.10
            mpmeet-wan:
                ipv4_address: 172.16.6.10
        ports:
            - 8081:8080
        volumes:
            - ./IIS/WebApi/Publish:/home/site/wwwroot
            - ./IIS/WebApi/logs:/var/log
        depends_on:
            - "mssql-server"


    web-app:
        image: "appsvc/dotnetcore:3.1-latest_20200522.6"
        container_name: web-app
        restart: always
        environment:
            WEBSITE_ROLE_INSTANCE_ID: localRoleInstance
            WEBSITE_INSTANCE_ID: localInstance
            ## Connection
            #Connection: "Server=27.72.195.144;initial catalog=MP_Meet;user id=sa;password=123@123a"
        networks:
            mpmeet-lan:
                ipv4_address: 10.0.6.11
            mpmeet-wan:
                ipv4_address: 172.16.6.11

        
        ports:
            - 8082:8080
        volumes:
            - ./IIS/WebApp/Publish:/home/site/wwwroot
            - ./IIS/WebApp/logs:/var/log
        depends_on:
            #- "mssql-server"
            - "web-api"

    # web-admin:
    #     image: "appsvc/dotnetcore:3.1-latest_20200522.6"
    #     container_name: web-admin
    #     restart: always
    #     environment:
    #         WEBSITE_ROLE_INSTANCE_ID: localRoleInstance
    #         WEBSITE_INSTANCE_ID: localInstance
    #         ## Connection
    #         #Connection: "Server=27.72.195.144;initial catalog=MP_Meet;user id=sa;password=123@123a"
    #     # networks:
    #     #     mpmeet-lan:
    #     #         ipv4_address: 10.0.6.10
    #     #     mpmeet-wan:
    #     #         ipv4_address: 172.16.6.10
    #     ports:
    #         - 8083:8080
    #     volumes:
    #         - ./IIS/WebAdmin/Publish:/home/site/wwwroot
    #         - ./IIS/WebAdmin/logs:/var/log
    #     depends_on:
    #         #- "mssql-server"
    #         - "web-api"


    # Cho thằng này vào để quản trị db, import mấy script ban đầu cũng tiện;
    # Không thì lại phải bind port ra host rồi vào;
    # mgmt-server:
    #     image: "adminer"
    #     container_name: mgmt-server
    #     restart: always
    #     environment:
    #         ADMINER_PLUGINS: "tables-filter tinymce"
    #         ADMINER_DESIGN: "nette"
    #         ADMINER_DEFAULT_SERVER: "mssql"
    #         # POSTGRES_HOST_AUTH_METHOD: "trust"
    #     # networks:
    #     #     mpmeet-lan:
    #     #         ipv4_address: 10.0.6.200
    #     #     mpmeet-wan:
    #     #         ipv4_address: 172.16.6.200
    #     volumes:
    #         - ./mgmt-server/html:/var/www/html
    #         - ./mgmt-server/mnt:/mnt
    #         - ./mgmt-server/logs:/var/log
    #     ports:
    #         - 8084:8080